//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sign.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AwsKmsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AwsKmsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sign.Cli.AwsKmsResources", typeof(AwsKmsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWS access key ID. If not provided, the default credential chain will be used..
        /// </summary>
        internal static string AccessKeyIdOptionDescription {
            get {
                return ResourceManager.GetString("AccessKeyIdOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate file not found: {0}.
        /// </summary>
        internal static string CertificateFileNotFound {
            get {
                return ResourceManager.GetString("CertificateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the certificate file (PEM or DER format) that corresponds to the KMS key..
        /// </summary>
        internal static string CertificatePathOptionDescription {
            get {
                return ResourceManager.GetString("CertificatePathOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign files using a key stored in AWS Key Management Service (KMS)..
        /// </summary>
        internal static string CommandDescription {
            get {
                return ResourceManager.GetString("CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate path..
        /// </summary>
        internal static string InvalidCertificatePath {
            get {
                return ResourceManager.GetString("InvalidCertificatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AWS region specified..
        /// </summary>
        internal static string InvalidRegion {
            get {
                return ResourceManager.GetString("InvalidRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AWS KMS key ID, key ARN, alias name, or alias ARN..
        /// </summary>
        internal static string KeyIdOptionDescription {
            get {
                return ResourceManager.GetString("KeyIdOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWS profile name from the credentials file. If not provided, the default credential chain will be used..
        /// </summary>
        internal static string ProfileOptionDescription {
            get {
                return ResourceManager.GetString("ProfileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AWS region where the KMS key is located (e.g., us-east-1)..
        /// </summary>
        internal static string RegionOptionDescription {
            get {
                return ResourceManager.GetString("RegionOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWS secret access key. Must be provided with --aws-access-key-id..
        /// </summary>
        internal static string SecretAccessKeyOptionDescription {
            get {
                return ResourceManager.GetString("SecretAccessKeyOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWS session token for temporary credentials..
        /// </summary>
        internal static string SessionTokenOptionDescription {
            get {
                return ResourceManager.GetString("SessionTokenOptionDescription", resourceCulture);
            }
        }
    }
}

